apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wanderlust
  labels:
    type: amazonEBS        # Label de diya taake PVC easily match kar sake
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # ✅ FIX: hostPath hata kar AWS Elastic Block Store lagaya hai
  awsElasticBlockStore:
    volumeID: "vol-0abcd1234abcd1234"  # 👈 Yahan apni asli AWS Volume ID likhein
    fsType: ext4