apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-087b98a18f3c673e3
    fsType: ext4
