apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: wanderlust
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.5-alpine   # ✅ Professional practice: Version specify kar diya jaisa docker-compose mein tha
          ports:
            - containerPort: 6379
          # ✅ FIX: Mongo ka volume reference yahan se mukammal remove kar diya hai taake koi data crash na ho
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: wanderlust
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP